name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-wasm32-emscripten:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: mymindstorm/setup-emsdk@v14
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "wasm32-unknown-emscripten"
      - name: CI-Build
        run: EMCMAKE=emcmake.bat cargo build --release --target=wasm32-unknown-emscripten
